version: "3.6"

services:
  public-api-gateway:
    image: nginx:latest
    volumes:
      - ./services/public-api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    depends_on:
      - books
      - users
      - auth

  auth:
    env_file: .env
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  books:
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: ./services/books/Dockerfile
    ports:
      - "${BOOKS_PORT}:${BOOKS_PORT}"
    depends_on:
      - books-db
    environment:
      WAIT_HOSTS: books-db:${BOOKS_MONGODB_PORT}

  users:
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: ./services/users/Dockerfile
    depends_on:
      - users-db
    environment:
      WAIT_HOSTS: users-db:${USERS_MONGODB_PORT}

  books-db:
    env_file: .env
    image: mongo:latest
    command: mongod -f /config.cfg --port ${BOOKS_MONGODB_PORT}
    volumes:
      - ./services/books-db/db:/data/db
      - ./services/books-db/config.cfg:/config.cfg
    ports:
      - ${BOOKS_MONGODB_PORT}:${BOOKS_MONGODB_PORT}

  users-db:
    image: mongo:latest
    command: mongod -f ./config.cfg --port ${USERS_MONGODB_PORT}
    volumes:
      - ./services/users-db/db:/data/db
      - ./services/users-db/config.cfg:/config.cfg
    ports:
      - ${USERS_MONGODB_PORT}:${USERS_MONGODB_PORT}
# volumes:
#   keys:
#     external: true
